name: Unit Test and E2E Test on Pull Request
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: npm install
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Unit Test
        run: npm run ci:test
      - name: Run E2E Test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
